-- Creation d'une db pour le stockage des donnees quotidiennes belib
CREATE TABLE "Records" (
	"ID" INTEGER NOT NULL UNIQUE, 
	"DATERECOLTE" TEXT NOT NULL, 
	"DISPONIBLE" INTEGER NOT NULL, 
	"OCCUPE" INTEGER NOT NULL, 
	"INCONNU" INTEGER, 
	"MAINTENANCE" INTEGER, 
	"RESERVE" INTEGER, 
	"NONIMPLEMENTE" INTEGER, 
	"SUPPRIME" INTEGER, 
	"ENCOURSMISESERVICE" INTEGER, 
	"MISESERVICEPLANIFIEE" INTEGER, 
	PRIMARY KEY("ID" AUTOINCREMENT)
);
